### PR TITLE
Update say.js

### PR DESCRIPTION
**Pull request by HyptexPvP**

### CODE REVIEW

**Comment by Steel-7777** [comment]
yes, but actually no.

**Comment by GhostSlayer** [comment]
Dont fuck with me

**Comment by HyptexPvP** [comment]
> Dont fuck with me

wdym?

**Comment by GhostSlayer** [comment]
> > Dont fuck with me
> 
> wdym?

i just put that as a joke :D

**Comment by HyptexPvP** [comment]
> > > Dont fuck with me
> > 
> > 
> > wdym?
> 
> i just put that as a joke :D

o

**Comment by danielpmc** [comment]
Uh no

**Pull request closed without merging**
