### PR TITLE
Made a small change to allow the use of lowercased prefix (DBH! -> dbh!)

### PR DESCRIPTION
**Pull request by FC5570**
a small change to allow use of lowercased prefix, both DBH! and dbh! will now work. thanks to micro for the suggestion (https://canary.discord.com/channels/639477525927690240/740302560488980561/808690122404003880). btw i didnt test it so test before merging, updated the messageEvent

### CODE REVIEW

**Comment by karelkryda** [comment]
@FC5570 revert changes....wrong line

It should be on line 57:
`if (message.content.toLowerCase().indexOf(prefix.toLowerCase()) !== 0) return;`

**Comment by FC5570** [comment]
> @FC5570 wrong line
> 
> It should be on line 57:
> `if (message.content.toLowerCase().indexOf(prefix.toLowerCase()) !== 0) return;`

guess i shouldnt have rushed things lmao, ill update it

**Comment by karelkryda** [comment]
> > @FC5570 wrong line
> > It should be on line 57:
> > `if (message.content.toLowerCase().indexOf(prefix.toLowerCase()) !== 0) return;`
> 
> guess i shouldnt have rushed things lmao, ill update it

`prefix.toLowerCase().length` and this is useless. Just change it back to `prefix.length`

**Comment by Hadimhz** [comment]
This won't even work since you didn't check if the lowercased prefix which will make it case insensitive.

**Comment by karelkryda** [comment]
> This won't even work since you didn't check if the lowercased prefix which will make it case insensitive.

what?

**Comment by somerandomcloud** [comment]
Dan wants it case sensitive pretty sure

**Comment by Hadimhz** [comment]
We'll leave the bot to be case-sensitive.

**Pull request closed without merging**
