### PR TITLE
Tags System: Helpful in notifying/Answering most common faqs

### PR DESCRIPTION
**Pull request by ManavvGarg**
yEA REview this and accept cause i am sick of telling people the same thing over and over again. This will help us to convey/answer questions. And will also help staff to not lose their mind because of answering stupid, weird and unnecessary questions.

Tags can only be created by admins and well ofc me. Feel free to make any change.

### CODE REVIEW

**Comment by RobinSchapendonk** [comment]
simp

**Comment by UnityLxthel** [comment]
This is v11

**Comment by UnityLxthel** [comment]
Bot is made in v12

**Comment by RobinSchapendonk** [comment]
nice

**Comment by FC5570** [comment]
lmfao is anyone ever gonna close this?

**Comment by Hadimhz** [comment]
We are not planning on adding another database to the bot.
this can simply be recreated using a JSON file (the file won't be changing that frequently so it shouldn't be a problem) or added to the SQLite database we already have.

**Pull request closed without merging**
